version: "3.0"
services:
  todo-api:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"
